Controllers/EmployeesListController.cs
using HRM_Project.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HRM_Project.Controllers
{
    public class EmployeesListController : Controller
    {
        private readonly HRM_DB_ProjectContext db;
        public EmployeesListController(HRM_DB_ProjectContext _db)
        {
            db = _db;
        }
        public IActionResult displayEmployees()
        {
            try
            {
                if (HttpContext.Session.GetString("Email") == null)
                {
                    return RedirectToAction("login_HR", "HrList");
                }
                string email = HttpContext.Session.GetString("Email");
                string location_name = db.HrLists.Include(hrl => hrl.Location).SingleOrDefault(x => x.HrEmail == email).Location.LocationName;
                ViewBag.location_name = location_name;
                var employees = db.EmployeesLists.Include(emp => emp.Location).Where(emp => emp.Location.LocationName == location_name).ToList();
                return View(employees);
            }
            catch(Exception e)
            {
                return RedirectToAction("handleException","Home", new { message = e.Message });
            }
        }
        public IActionResult add_Employee()
        {
            try
            {
                if (HttpContext.Session.GetString("Email") == null)
                {
                    return RedirectToAction("login_HR", "HrList");
                }
                string hr_location = HttpContext.Session.GetString("Location");
                ViewBag.LocationId = db.LocationLists.FirstOrDefault(x => x.LocationId == hr_location).LocationId;
                return View();
            }
            catch (Exception e)
            {
                return RedirectToAction("handleException", "Home", new { message = e.Message });
            }
        }
        [HttpPost]
        public IActionResult add_Employee(EmployeesList employee)
        {
            try
            {
                if (HttpContext.Session.GetString("Email") == null)
                {
                    return RedirectToAction("login_HR", "HrList");
                }
                db.EmployeesLists.Add(employee);
                db.SaveChanges();
                return RedirectToAction("displayEmployees");
            }
            catch (Exception e)
            {
                return RedirectToAction("handleException", "Home", new { message = e.Message });
            }
        }
        public IActionResult open_Employee(int id)
        {
            try
            {
                if (HttpContext.Session.GetString("Email") == null)
                {
                    return RedirectToAction("login_HR", "HrList");
                }
                EmployeesList employee = db.EmployeesLists.Include(x => x.Location).SingleOrDefault(emp => emp.EmployeeId == id);
                ViewBag.locations = db.LocationLists.Select(x => new SelectListItem { Value = x.LocationId.ToString(), Text = x.LocationName }).ToList();
                ViewBag.eligible = (employee.EmployeeAppraisalDate <= DateTime.Today);
                return View(employee);
            }
            catch (Exception e)
            {
                return RedirectToAction("handleException", "Home", new { message = e.Message });
            }
        }
        [HttpPost]
        public IActionResult incrementSalary(EmployeesList employee)
        {
            try
            {
                if (HttpContext.Session.GetString("Email") == null)
                {
                    return RedirectToAction("login_HR", "HrList");
                }
                EmployeesList emp = db.EmployeesLists.SingleOrDefault(emp => emp.EmployeeId == employee.EmployeeId);
                emp.EmployeeSalary = employee.EmployeeSalary;
                emp.EmployeeAppraisalDate = DateTime.Today.AddYears(1);
                db.EmployeesLists.Update(emp);
                db.SaveChanges();
                return RedirectToAction("open_Employee", new { id = employee.EmployeeId });
            }
            catch (Exception e)
            {
                return RedirectToAction("handleException", "Home", new { message = e.Message });
            }
        }
        [HttpPost]
        public IActionResult editDetails(EmployeesList employee)
        {
            try
            {
                if (HttpContext.Session.GetString("Email") == null)
                {
                    return RedirectToAction("login_HR", "HrList");
                }
                db.EmployeesLists.Update(employee);
                db.SaveChanges();
                return RedirectToAction("displayEmployees");
            }
            catch (Exception e)
            {
                return RedirectToAction("handleException", "Home", new { message = e.Message });
            }
        }
        [HttpPost]
        public IActionResult fireEmployee(EmployeesList employee)
        {
            try
            {
                if (HttpContext.Session.GetString("Email") == null)
                {
                    return RedirectToAction("login_HR", "HrList");
                }
                db.EmployeesLists.Remove(employee);
                db.SaveChanges();
                return RedirectToAction("displayEmployees");
            }
            catch (Exception e)
            {
                return RedirectToAction("handleException", "Home", new { message = e.Message });
            }
        }
        [HttpPost]
        public IActionResult transferEmployee(EmployeesList employee)
        {
            try
            {
                if (HttpContext.Session.GetString("Email") == null)
                {
                    return RedirectToAction("login_HR", "HrList");
                }
                EmployeesList employee1 = db.EmployeesLists.SingleOrDefault(emp => emp.EmployeeId == employee.EmployeeId);
                employee1.LocationId = employee.LocationId;
                db.EmployeesLists.Update(employee1);
                db.SaveChanges();
                return RedirectToAction("displayEmployees");
            }
            catch (Exception e)
            {
                return RedirectToAction("handleException", "Home", new { message = e.Message });
            }
        }
    }
}

Controllers/HomeController.cs
using HRM_Project.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace HRM_Project.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly HRM_DB_ProjectContext db;

        public HomeController(ILogger<HomeController> logger, HRM_DB_ProjectContext _db)
        {
            _logger = logger;
            db = _db;
        }
        public IActionResult handleException(string message = "Exception")
        {
            ViewBag.Emessage = message;
            return View();
        }
        public IActionResult Index()
        {
            try
            {
                ViewBag.all_locations = db.LocationLists.ToList();
                if (HttpContext.Session.GetString("Email") != null)
                {
                    string email = HttpContext.Session.GetString("Email");
                    string location_name = db.HrLists.Include(hrl => hrl.Location).SingleOrDefault(x => x.HrEmail == email).Location.LocationName;
                    ViewBag.location = location_name;
                    return View();
                }
                return View();
            }
            catch (Exception e)
            {
                return RedirectToAction("handleException", "Home", new { message = e.Message });
            }
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<style>
    .main-box {
        margin-top: 25px;
        width: 100%;
        height: 100%;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center
    }

    .left-box {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        margin: 25px;
    }

    .right-box {
        display: flex;
        flex-direction: column;
        justify-content: center;
    }

    .h4-rightBox {
        font-size: 22px;
    }

    .a-rightBox {
        color:lightgray;
        font-style: italic;
        padding: 10px;
        text-decoration: none;
        border-radius: 3px;
        margin: 10px;
        border: 3px solid #ededed;
    }

    .a-rightBox:hover {
        background-color: #ededed;
        color: navy;
    }

    .locations-span {
        margin: 15px;
        color: #d9d9d9;
    }

    .box-for-span {
        margin-top: 20px;
    }
</style>
<div class="main-box">
    <div class="left-box text-center">
        <h1 style="color: #d9d9d9; font-style: italic; font-weight: bold" class="display-3">
            Human Resource
            <br /><span style="color: #d9d9d9; font-weight: bold" class="display-4">
                        Manager!
                        <i class="fas fa-dragon"></i>
                  </span>
        </h1>
        <div class="box-for-span">
            <i class='fas fa-map-marker-alt' style='font-size: 20px; color: #d9d9d9'></i>
            @foreach (var location in ViewBag.all_locations)
            {
                <span class="locations-span">
                    @location.LocationName
                </span>
            }
        </div>
    </div>
    @if (ViewBag.login != null)
    {
        <div style="border-top:2px solid white" class="right-box text-center">
            <h4 style="color:white;" class="h4-rightBox">Manage</h4>
            <a class="a-rightBox" asp-controller="EmployeesList" asp-action="displayEmployees">Employees in @ViewBag.location</a>
            <a class="a-rightBox" asp-controller="HrList" asp-action="edit_HR">Edit Account</a>
        </div>
    }
</div>

<script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>

Views/Home/handleException.cshtml
@*
*@
@{
}
<div>
    <a style="color:#ededed" asp-controller="Home" asp-action="Index">
        <i class="fa fa-arrow-left"></i> Back
    </a>
</div>
<hr />
<p style="color:#ededed" class="display-3">Exception Caught!</p>
<h3 style="color:#ededed" class="display-4">@ViewBag.Emessage</h3>